// ─── Enums ───────────────────────────────────────────────────────────────────

export type TunnelType = 'file' | 'http' | 'tcp' | 'udp' | 'p2p';
export type EntrypointType = 'tcp' | 'udp' | 'p2p';
export type ServiceStatus = 'running' | 'stopped' | 'error';
export type ThemePreference = 'system' | 'light' | 'dark';
export type LanguagePreference = 'en' | 'zh';

export const TUNNEL_TYPES: { value: TunnelType; label: string; desc: string }[] = [
  { value: 'file', label: 'File', desc: '' },
  { value: 'http', label: 'HTTP', desc: '' },
  { value: 'tcp', label: 'TCP', desc: '' },
  { value: 'udp', label: 'UDP', desc: '' },
  { value: 'p2p', label: 'P2P', desc: '' },
];

export const ENTRYPOINT_TYPES: { value: EntrypointType; label: string; desc: string }[] = [
  { value: 'tcp', label: 'TCP', desc: '' },
  { value: 'udp', label: 'UDP', desc: '' },
  { value: 'p2p', label: 'P2P', desc: '' },
];

// ─── Stats ───────────────────────────────────────────────────────────────────

export interface ServiceStats {
  current_conns: number;
  total_conns: number;
  total_errs: number;
  request_rate: number;
  input_bytes: number;
  output_bytes: number;
  input_rate_bytes: number;
  output_rate_bytes: number;
}

export interface ItemStats {
  current_conns: number;
  total_conns: number;
  total_errs: number;
  request_rate: number;
  input_bytes: number;
  output_bytes: number;
  input_rate_bytes: number;
  output_rate_bytes: number;
}

// ─── Tunnel ──────────────────────────────────────────────────────────────────

/** One p2p allowlist entry: the key is the credential, the alias its display
 *  name (generated by the backend when not given). */
export interface Peer {
  key: string;
  alias?: string;
}

export interface TunnelOptions {
  prefix?: string;
  hostname: string;
  username: string;
  password: string;
  basic_auth: boolean;
  enableTLS: boolean;
  rewriteHost: boolean;
  file_upload: boolean;
  keepalive: boolean;
  ttl: number;
  record_mode: string;
  /** Remote peer's base64 public key (p2p entrypoints). */
  peer?: string;
  /** Inbound allowlist: the peers whose streams reach this p2p tunnel. Empty = unreachable. */
  peers?: Peer[];
}

/** One peer's traffic during the tunnel's current run. */
export interface PeerStats {
  key: string;
  alias?: string;
  current_conns: number;
  total_conns: number;
  input_bytes: number;
  output_bytes: number;
  input_rate_bytes: number;
  output_rate_bytes: number;
}

export interface Tunnel {
  id: string;
  name: string;
  type: TunnelType;
  endpoint: string;
  entrypoint: string;
  status: ServiceStatus;
  favorite: boolean;
  created_at: string;
  error: string;
  options: TunnelOptions;
  stats: ServiceStats;
  /** p2p tunnels: per-peer traffic, allowlist order. */
  peer_stats?: PeerStats[];
}

export interface TunnelCreateRequest {
  name: string;
  type: TunnelType;
  endpoint: string;
  prefix?: string;
  hostname?: string;
  username?: string;
  password?: string;
  enableTLS?: boolean;
  rewriteHost?: boolean;
  file_upload?: boolean;
  record_mode?: string;
  /** Remote peer's base64 public key (p2p entrypoints). */
  peer?: string;
  /** Inbound allowlist: the peers whose streams reach this p2p tunnel. An
   *  entry's alias may be omitted — the backend generates one. */
  peers?: Peer[];
}

// ─── Entrypoint ──────────────────────────────────────────────────────────────

export interface EntrypointOptions {
  keepalive: boolean;
  ttl: number;
  /** Remote peer's base64 public key (p2p entrypoints). */
  peer?: string;
  /** A p2p entrypoint's inner protocol: 'tcp' (default) or 'udp'. */
  protocol?: string;
}

export interface Entrypoint {
  id: string;
  name: string;
  type: EntrypointType;
  endpoint: string;
  entrypoint: string;
  status: ServiceStatus;
  favorite: boolean;
  created_at: string;
  error: string;
  options: EntrypointOptions;
  stats: ServiceStats;
}

/** TunnelPeersRequest replaces a p2p tunnel's allowlist on its own. */
export interface TunnelPeersRequest {
  peers: Peer[];
}

export interface EntrypointCreateRequest {
  name: string;
  type: EntrypointType;
  endpoint: string;
  tunnel_id?: string;
  keepalive?: boolean;
  ttl?: number;
  /** Remote peer's base64 public key (p2p entrypoints). */
  peer?: string;
  /** A p2p entrypoint's inner protocol: 'tcp' (default) or 'udp'. */
  protocol?: string;
}

// ─── Stats Snapshot ──────────────────────────────────────────────────────────

export interface StatsSnapshot {
  tunnels: Tunnel[];
  entrypoints: Entrypoint[];
}

// ─── App Settings ────────────────────────────────────────────────────────────

/** Private p2p mode settings. Empty `derp` means the default public relay. */
export interface P2PSettings {
  derp: string;
  secure?: boolean;
  ca_file?: string;
  /** STUN server for the IPv4 direct path; empty = the relay host on :3478. */
  stun?: string;
  /** Attempt a direct (hole-punched) path; omitted = true. */
  direct?: boolean;
}

export interface AppSettings {
  server: string;
  entrypoint: string;
  insecure: boolean;
  lang: LanguagePreference;
  theme: ThemePreference;
  stats_interval: number;
  inspector_url?: string;
  p2p?: P2PSettings;
}

export interface AppSettingsUpdate {
  server?: string;
  entrypoint?: string;
  insecure?: boolean;
  lang?: string;
  theme?: string;
  stats_interval?: number;
  inspector_url?: string;
  p2p?: P2PSettings;
}

// ─── Inspector ───────────────────────────────────────────────────────────

/** HTTP header map, as serialized from Go's `http.Header` (`map[string][]string`). */
export type HttpHeaders = Record<string, string[]>;

export interface HttpRecord {
  host: string;
  method: string;
  proto: string;
  scheme: string;
  uri: string;
  statusCode: number;
  request: { header: HttpHeaders | null; body: string | null };   // null when from list (excluded via projection)
  response: { header: HttpHeaders | null; body: string | null };  // null when from list
}

export interface WsRecord {
  from: string;
  fin: boolean;
  rsv1: boolean;
  rsv2: boolean;
  rsv3: boolean;
  opcode: number;
  masked: boolean;
  maskKey?: number;
  length: number;
  payload: string | null;  // null when from list
}

export interface InspectorRecord {
  id?: string;          // MongoDB ObjectID hex — set from list cursor & detail endpoint
  node?: string;
  service: string;
  network: string;
  remote: string;
  local: string;
  host: string;
  dst: string;
  proto?: string;
  clientIP: string;
  clientID?: string;
  http?: HttpRecord;
  websocket?: WsRecord;
  route?: string;
  inputBytes: number;
  outputBytes: number;
  redirect?: string;
  err?: string;
  sid: string;
  duration: number;
  time: string;
}

export interface InspectorQueryResponse {
  code: number;
  data: {
    list: InspectorRecord[];
    before?: string;
    after?: string;
  };
  msg: string;
  error?: string;
}

export type ProtocolType = 'http' | 'websocket';

// ─── Version ───────────────────────────────────────────────────────────

/** Response from GET /api/version. */
export interface VersionInfo {
  version: string;
}
