// ─── Enums ───────────────────────────────────────────────────────────────────

export type TunnelType = 'file' | 'http' | 'tcp' | 'udp' | 'p2p' | 'tun';
export type EntrypointType = 'tcp' | 'udp' | 'p2p' | 'tun';
export type ServiceStatus = 'running' | 'stopped' | 'error';
export type ThemePreference = 'system' | 'light' | 'dark';
export type LanguagePreference = 'en' | 'zh';

export const TUNNEL_TYPES: { value: TunnelType; label: string; desc: string }[] = [
  { value: 'file', label: 'File', desc: '' },
  { value: 'http', label: 'HTTP', desc: '' },
  { value: 'tcp', label: 'TCP', desc: '' },
  { value: 'udp', label: 'UDP', desc: '' },
  { value: 'p2p', label: 'P2P', desc: '' },
  { value: 'tun', label: 'TUN', desc: '' },
];

export const ENTRYPOINT_TYPES: { value: EntrypointType; label: string; desc: string }[] = [
  { value: 'tcp', label: 'TCP', desc: '' },
  { value: 'udp', label: 'UDP', desc: '' },
  { value: 'p2p', label: 'P2P', desc: '' },
  { value: 'tun', label: 'TUN', desc: '' },
];

// ─── Stats ───────────────────────────────────────────────────────────────────

export interface ServiceStats {
  current_conns: number;
  total_conns: number;
  total_errs: number;
  request_rate: number;
  input_bytes: number;
  output_bytes: number;
  input_rate_bytes: number;
  output_rate_bytes: number;
  /** LAN routes a tun hub installed (absent everywhere else). */
  lan_routed?: number;
  /** LAN claims a tun hub refused. */
  lan_denied?: number;
  /** LAN routes a tun hub withdrew. */
  lan_withdrawn?: number;
}

export interface ItemStats {
  current_conns: number;
  total_conns: number;
  total_errs: number;
  request_rate: number;
  input_bytes: number;
  output_bytes: number;
  input_rate_bytes: number;
  output_rate_bytes: number;
  lan_routed?: number;
  lan_denied?: number;
  lan_withdrawn?: number;
}

// ─── Tunnel ──────────────────────────────────────────────────────────────────

/** One p2p allowlist entry: the key is the credential, the alias its display
 *  name (generated by the backend when not given). */
export interface Peer {
  key: string;
  alias?: string;
  /** Switched off: the peer keeps its place on the list but gets no route, so
   *  its new streams are closed while established ones drain. */
  disabled?: boolean;
  /** The address this peer may claim on the hub's device network (host
   *  addresses, comma-separated; never a prefix). Absent when the row holds
   *  none — the hub allocates one on the next save. A p2p tunnel has no device
   *  network, so its rows never carry it. */
  ip?: string;
}

export interface TunnelOptions {
  prefix?: string;
  hostname: string;
  username: string;
  password: string;
  basic_auth: boolean;
  enableTLS: boolean;
  rewriteHost: boolean;
  file_upload: boolean;
  keepalive: boolean;
  ttl: number;
  record_mode: string;
  /** Remote peer's base64 public key (p2p entrypoints). */
  peer?: string;
  /** Inbound allowlist: the peers whose streams reach this p2p tunnel. Empty = unreachable. */
  peers?: Peer[];
  /** tun device address (CIDR, comma-separated for several). */
  net?: string;
  /** tun device MTU (absent = the implementation default, 1420). */
  mtu?: number;
  /** tun device name (absent = kernel-chosen). */
  device_name?: string;
  /** Subnets routed through the device, comma-separated "cidr [gw]" pairs. */
  routes?: string;
  /** The device's DNS servers, comma-separated. */
  dns?: string;
  /** Hub-side LAN subnets shared with peers (comma-separated CIDRs, empty disables). */
  share_lan?: string;
  /** Sharing backend: 'auto' (default), 'kernel', or 'userspace'. */
  share_mode?: string;
}

/** One peer's traffic during the tunnel's current run, plus the p2p host's

/** One peer's traffic during the tunnel's current run, plus the p2p host's
 *  live diagnostic for it. The diagnostic fields are absent until the peer has
 *  a session (and on an older p2p that does not report them). */
export interface PeerStats {
  key: string;
  alias?: string;
  /** Where this peer's traffic goes now: 'direct' or 'derp'; absent when it
   *  has no session at all. */
  transport?: string;
  /** Host-wide cause when it outranks the peer's own round ('no-candidates',
   *  'stun-unreachable', 'disabled'); verbatim p2p wire values. */
  reason?: string;
  /** The punch state machine: 'none' | 'attempting' | 'up' | 'backoff'. */
  state?: string;
  /** A punch round has failed (sticky); independent of the current state. */
  failed?: boolean;
  /** The last punch failure's reason (absent after a success). */
  last_error?: string;
  /** The endpoint dialled for the direct path (absent until a round dials). */
  peer_addr?: string;
  /** How many candidates the peer announced. */
  candidates?: number;
  /** The peer's advertised capabilities ('ipv6', 'tightKeepalive'). */
  caps?: string[];
  /** How long the live direct session has been up (0 when none). */
  session_age_ms?: number;
  /** How long since the last frame from the peer. */
  last_recv_age_ms?: number;
  /** The peer's recent punch history: short lines, oldest first (newest kept),
   *  capped by the p2p host's ring. */
  trace?: string[];
  /** The LANs this peer holds on the hub's network — the CIDRs it claimed.
   *  Absent when it holds none (and on an object that has no device network). */
  lan?: string[];
  current_conns: number;
  total_conns: number;
  input_bytes: number;
  output_bytes: number;
  input_rate_bytes: number;
  output_rate_bytes: number;
}

/** One recorded occurrence in a tunnel's, entrypoint's, or the host's history.
 *  Named WisperEvent rather than Event: the DOM's global Event type would be
 *  shadowed in every module that imports this. */
export interface WisperEvent {
  time: string;
  level: 'info' | 'warn' | 'error';
  message: string;
  /** Run length of a coalesced repeat (1 for a one-off). A pre-count event
   *  carries 0 and should be read as 1. */
  count?: number;
}

/** One LAN route a tun hub installed: the CIDR, who put it there (a spoke's
 *  key, or 'static' for the hub's own config), the member that carries it, and
 *  the members allowed to use it (absent = all of them). */
export interface LANRoute {
  prefix: string;
  origin: string;
  peer: string;
  allow?: string[];
}

/** One claim a tun hub turned down: the CIDR, the spoke that asked, the RIB's
 *  reason code, the sentence an operator reads, and when. A refusal is never
 *  revoked and its prefix never reaches the routes table, which is why the two
 *  lists are read together. */
export interface LANRefusal {
  prefix: string;
  peer: string;
  reason: string;
  detail?: string;
  at: string;
}

/** A tun hub's LAN routing, as one read of its RIB: the installed table, each
 *  spoke's claim of it, and what was refused. Only a running hub reports one,
 *  so every other object — and a hub whose control channel never opened —
 *  leaves the field absent. */
export interface TunnelLAN {
  routes: LANRoute[];
  claims: Record<string, { prefixes: string[]; allow?: string[] }>;
  rejected?: LANRefusal[];
}

export interface Tunnel {
  id: string;
  name: string;
  type: TunnelType;
  endpoint: string;
  entrypoint: string;
  status: ServiceStatus;
  favorite: boolean;
  created_at: string;
  error: string;
  options: TunnelOptions;
  stats: ServiceStats;
  /** p2p tunnels: per-peer traffic, allowlist order. */
  peer_stats?: PeerStats[];
  /** tun hubs: the LAN routing state (absent on everything else). */
  lan?: TunnelLAN;
  /** p2p entrypoints: where the peer's traffic goes now ('direct'/'derp'). */
  peer_transport?: string;
  /** tun hubs: the sharing backend actually settled on ('kernel'/'userspace', absent when disabled). */
  share_effective?: string;
  /** True when auto fell back to userspace — the badge that explains why ping fails. */
  share_downgraded?: boolean;
  /** This object's recent history, newest first. */
  events?: WisperEvent[];
}

export interface TunnelCreateRequest {
  name: string;
  type: TunnelType;
  endpoint: string;
  prefix?: string;
  hostname?: string;
  username?: string;
  password?: string;
  enableTLS?: boolean;
  rewriteHost?: boolean;
  file_upload?: boolean;
  keepalive?: boolean;
  ttl?: number;
  record_mode?: string;
  /** Remote peer's base64 public key (p2p entrypoints). */
  peer?: string;
  /** Inbound allowlist: the peers whose streams reach this p2p tunnel. An
   *  entry's alias may be omitted — the backend generates one. */
  peers?: Peer[];
  /** tun device address (CIDR, comma-separated for several). */
  net?: string;
  mtu?: number;
  device_name?: string;
  /** Subnets routed through the device, comma-separated "cidr [gw]" pairs. */
  routes?: string;
  dns?: string;
  /** Hub-side LAN subnets shared with peers (comma-separated CIDRs, empty disables). */
  share_lan?: string;
  /** Sharing backend: 'auto' (default), 'kernel', or 'userspace'. */
  share_mode?: string;
}

// ─── Entrypoint ──────────────────────────────────────────────────────────────

export interface EntrypointOptions {
  keepalive: boolean;
  probe: boolean;
  ttl: number;
  /** Remote peer's base64 public key (p2p entrypoints). */
  peer?: string;
  /** A p2p entrypoint's inner protocol: 'tcp' (default) or 'udp'. */
  protocol?: string;
  /** tun device address (CIDR, comma-separated for several). */
  net?: string;
  mtu?: number;
  device_name?: string;
  /** Subnets routed through the device, comma-separated "cidr [gw]" pairs. */
  routes?: string;
  dns?: string;
  /** Hub-side LAN subnets shared with peers (comma-separated CIDRs, empty disables). */
  share_lan?: string;
  /** Sharing backend: 'auto' (default), 'kernel', or 'userspace'. */
  share_mode?: string;
}

export interface Entrypoint {
  id: string;
  name: string;
  type: EntrypointType;
  endpoint: string;
  entrypoint: string;
  status: ServiceStatus;
  favorite: boolean;
  created_at: string;
  error: string;
  options: EntrypointOptions;
  stats: ServiceStats;
  /** p2p entrypoints: where the peer's traffic goes now ('direct'/'derp'). */
  peer_transport?: string;
  /** tun entrypoints: the LANs this spoke's hub approved and installed, which
   *  is what became of its share_lan rather than what it asked for. Absent
   *  when the hub approved nothing. */
  lan_routes?: string[];
  /** This object's recent history, newest first. */
  events?: WisperEvent[];
}

/** TunnelPeersRequest replaces a p2p tunnel's allowlist on its own. */
export interface TunnelPeersRequest {
  peers: Peer[];
}

export interface EntrypointCreateRequest {
  name: string;
  type: EntrypointType;
  endpoint: string;
  tunnel_id?: string;
  keepalive?: boolean;
  probe?: boolean;
  ttl?: number;
  /** Remote peer's base64 public key (p2p entrypoints). */
  peer?: string;
  /** A p2p entrypoint's inner protocol: 'tcp' (default) or 'udp'. */
  protocol?: string;
  /** tun device address (CIDR, comma-separated for several). */
  net?: string;
  mtu?: number;
  device_name?: string;
  /** Subnets routed through the device, comma-separated "cidr [gw]" pairs. */
  routes?: string;
  dns?: string;
  /** Hub-side LAN subnets shared with peers (comma-separated CIDRs, empty disables). */
  share_lan?: string;
  /** Sharing backend: 'auto' (default), 'kernel', or 'userspace'. */
  share_mode?: string;
}

// ─── Stats Snapshot ──────────────────────────────────────────────────────────

export interface StatsSnapshot {
  tunnels: Tunnel[];
  entrypoints: Entrypoint[];
}

// ─── App Settings ────────────────────────────────────────────────────────────

/** Private p2p mode settings. Empty `derp` means the default public relay. */
export interface P2PSettings {
  derp: string;
  secure?: boolean;
  ca_file?: string;
  /** STUN server for the IPv4 direct path; empty = the relay host on :3478. */
  stun?: string;
  /** Attempt a direct (hole-punched) path; omitted = true. */
  direct?: boolean;
}

export interface AppSettings {
  server: string;
  entrypoint: string;
  insecure: boolean;
  lang: LanguagePreference;
  theme: ThemePreference;
  stats_interval: number;
  inspector_url?: string;
  p2p?: P2PSettings;
}

export interface AppSettingsUpdate {
  server?: string;
  entrypoint?: string;
  insecure?: boolean;
  lang?: string;
  theme?: string;
  stats_interval?: number;
  inspector_url?: string;
  p2p?: P2PSettings;
}

// ─── Inspector ───────────────────────────────────────────────────────────

/** HTTP header map, as serialized from Go's `http.Header` (`map[string][]string`). */
export type HttpHeaders = Record<string, string[]>;

export interface HttpRecord {
  host: string;
  method: string;
  proto: string;
  scheme: string;
  uri: string;
  statusCode: number;
  request: { header: HttpHeaders | null; body: string | null };   // null when from list (excluded via projection)
  response: { header: HttpHeaders | null; body: string | null };  // null when from list
}

export interface WsRecord {
  from: string;
  fin: boolean;
  rsv1: boolean;
  rsv2: boolean;
  rsv3: boolean;
  opcode: number;
  masked: boolean;
  maskKey?: number;
  length: number;
  payload: string | null;  // null when from list
}

export interface InspectorRecord {
  id?: string;          // MongoDB ObjectID hex — set from list cursor & detail endpoint
  node?: string;
  service: string;
  network: string;
  remote: string;
  local: string;
  host: string;
  dst: string;
  proto?: string;
  clientIP: string;
  clientID?: string;
  http?: HttpRecord;
  websocket?: WsRecord;
  route?: string;
  inputBytes: number;
  outputBytes: number;
  redirect?: string;
  err?: string;
  sid: string;
  duration: number;
  time: string;
}

export interface InspectorQueryResponse {
  code: number;
  data: {
    list: InspectorRecord[];
    before?: string;
    after?: string;
  };
  msg: string;
  error?: string;
}

export type ProtocolType = 'http' | 'websocket';

// ─── Pending peers ───────────────────────────────────────────────────────────

/** One key that knocked on the p2p host without being on any allowlist. */
export interface PendingPeer {
  key: string;
  first_seen: string;
  last_seen: string;
  attempts: number;
}

// ─── Version ───────────────────────────────────────────────────────────

/** Response from GET /api/version. */
export interface VersionInfo {
  version: string;
}
