// JNI bridge — thin wrappers that map JNI calling conventions (expected by
// Kotlin's System.loadLibrary + external fun) to Go-exported C functions
// (generated by //export in lib.go).
//
// Compiled with CGO_ENABLED=1 GOOS=android GOARCH=arm64.
// cgo auto-compiles .c files in the Go package directory.

#include <jni.h>
#include <string.h>

// Go exports (generated by //export in lib.go).
extern int wisperStartGo(char* configDir, char* addr);
extern void wisperStopGo();

JNIEXPORT jint JNICALL
Java_run_gost_wisper_WisperJNI_start(JNIEnv *env, jclass clazz,
	jstring configDir, jstring addr) {
	const char *configDirC = (*env)->GetStringUTFChars(env, configDir, NULL);
	const char *addrC      = (*env)->GetStringUTFChars(env, addr, NULL);

	jint result = wisperStartGo((char*)configDirC, (char*)addrC);

	(*env)->ReleaseStringUTFChars(env, configDir, configDirC);
	(*env)->ReleaseStringUTFChars(env, addr, addrC);

	return result;
}

JNIEXPORT void JNICALL
Java_run_gost_wisper_WisperJNI_stop(JNIEnv *env, jclass clazz) {
	wisperStopGo();
}
