#!/usr/bin/env python3
"""Generate every Wisper branding asset from appicon.png.

Single source of truth: appicon.png (512x512 RGBA, white ghost on solid
black square) at the repo root. Run this whenever appicon.png changes.

All output icons use the same ghost-isolation pipeline: crop to the ghost
body, flood-fill residual black to transparent, tight crop, pad to square
with transparent margin, resize.

Outputs (all created/overwritten, idempotent):
  src-tauri/icons/32x32.png         desktop icon set (RGBA PNGs — Tauri on
  src-tauri/icons/128x128.png        Linux requires RGBA, not RGB)
  src-tauri/icons/128x128@2x.png    (256x256)
  src-tauri/icons/icon.png          (1024x1024, upscaled)
  src-tauri/icons/icon.ico          Windows multi-resolution icon
  src-tauri/icons/tray.png          system tray icon
  web-src/public/logo.png           in-app logo (displayed at 28px & 64px)
  web-src/public/favicon.ico        browser tab icon

.icns (macOS) is generated by Pillow's ICNS format via pack_icns().
"""
import os
import sys

from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "appicon.png")

ICONS_DIR = os.path.join(ROOT, "src-tauri", "icons")
PUBLIC_DIR = os.path.join(ROOT, "web-src", "public")

# (px, path)
PNG_SET = [
    (32, "32x32.png"),
    (128, "128x128.png"),
    (256, "128x128@2x.png"),
    (1024, "icon.png"),
]

# Multi-resolution .ico sizes (Pillow writes all into one file).
ICO_SIZES = [16, 24, 32, 48, 64, 128, 256]
FAVICON_SIZES = [16, 32, 48]
# Standard macOS .icns sizes (Pillow maps these to icp4–ic10 types).
ICNS_SIZES = [16, 32, 64, 128, 256, 512, 1024]

LOGO_PX = 256
TRAY_PX = 128


def make_ghost_icon(src: Image.Image, dest: str, px: int) -> None:
    """Isolate the ghost on a transparent background.

    The source is a white ghost on a solid black square; we want only the
    ghost, cropped tight against its body, on a fully transparent background.

    Two stages (flood-fill alone is fragile — anti-aliased dark fringe pixels
    stay opaque and inflate the bounding box):
      1. Bounding box from *bright* (ghost-body) pixels — dark fringe and stray
         pixels are ignored, so the box is the true ghost extent.
      2. Crop to that box, then flood-fill the residual black background
         (corners + gaps between the ghost's wavy tendrils) to transparent.
         The eyes are interior black, disconnected from the border, so they
         survive.

    Then a final tight crop, pad to a square with a small transparent margin,
    and resize.
    """
    img = src.convert("RGBA")
    W, H = img.size

    # Stage 1 — bbox of the bright ghost body (immune to dark fringe/strays).
    bright = img.convert("L").point(lambda v: 255 if v > 100 else 0)
    bbox = bright.getbbox() or (0, 0, W, H)
    l, t, r, b = bbox
    pad = max(4, int(max(W, H) * 0.02))  # don't clip the body's outer edge
    img = img.crop((max(0, l - pad), max(0, t - pad), min(W, r + pad), min(H, b + pad)))

    # Stage 2 — remove the residual black background by flood-filling from
    # each corner to transparent.
    cw, ch = img.size
    for corner in [(0, 0), (cw - 1, 0), (0, ch - 1), (cw - 1, ch - 1)]:
        ImageDraw.floodfill(img, corner, value=(0, 0, 0, 0), thresh=50)

    # Final tight crop to the ghost, pad to a square with a ~6% transparent
    # margin so the ghost isn't edge-to-edge, and resize.
    bb = img.getbbox()
    if bb:
        img = img.crop(bb)
    side = max(img.width, img.height)
    margin = int(side * 0.06)
    canvas = side + 2 * margin
    out = Image.new("RGBA", (canvas, canvas), (0, 0, 0, 0))
    out.paste(img, ((canvas - img.width) // 2, (canvas - img.height) // 2), img)
    out.resize((px, px), Image.Resampling.LANCZOS).save(dest, format="PNG")


def pack_ico(src: Image.Image, dest: str, sizes: list[int]) -> None:
    """Pack `src` (RGBA, ghost-on-transparent) into a multi-resolution .ico."""
    tmp = os.path.join(ICONS_DIR, "_ico_tmp.png")
    make_ghost_icon(src, tmp, max(sizes))
    ico_src = Image.open(tmp).convert("RGBA")
    ico_src.save(dest, format="ICO", sizes=[(s, s) for s in sizes])
    os.remove(tmp)


def pack_icns(src: Image.Image, dest: str, sizes: list[int]) -> None:
    """Pack `src` (RGBA, ghost-on-transparent) into a macOS .icns file.

    Pillow ≥9.1 writes ICNS with the main image plus an append_images list
    for the smaller representations (icp4 through ic09). The main image
    should be the largest size (1024 px → ic10). All are derived from the
    same ghost-isolated source.
    """
    largest = max(sizes)
    smaller = sorted(s for s in sizes if s != largest)
    tmp_dir = os.path.join(ICONS_DIR, "_icns_tmp")
    os.makedirs(tmp_dir, exist_ok=True)

    # Generate the largest icon as the primary image.
    main_path = os.path.join(tmp_dir, f"icon_{largest}.png")
    make_ghost_icon(src, main_path, largest)
    main_img = Image.open(main_path).convert("RGBA")

    # Generate smaller sizes for append_images.
    smaller_imgs = []
    for px in smaller:
        sp = os.path.join(tmp_dir, f"icon_{px}.png")
        make_ghost_icon(src, sp, px)
        smaller_imgs.append(Image.open(sp).convert("RGBA"))

    main_img.save(dest, format="ICNS", append_images=smaller_imgs)

    # Cleanup.
    for img in [main_img] + smaller_imgs:
        img.close()
    for f in sorted(os.listdir(tmp_dir)):
        os.remove(os.path.join(tmp_dir, f))
    os.rmdir(tmp_dir)


def main() -> int:
    if not os.path.isfile(SRC):
        print(f"error: source logo not found at {SRC}", file=sys.stderr)
        return 1

    src = Image.open(SRC)
    if src.mode != "RGBA":
        src = src.convert("RGBA")
    print(f"source: {SRC}  {src.size[0]}x{src.size[1]} {src.mode}")

    os.makedirs(ICONS_DIR, exist_ok=True)
    os.makedirs(PUBLIC_DIR, exist_ok=True)

    # --- desktop PNG set ---
    for px, name in PNG_SET:
        dest = os.path.join(ICONS_DIR, name)
        make_ghost_icon(src, dest, px)
        print(f"  wrote {os.path.relpath(dest, ROOT)} ({px}x{px}, transparent bg)")

    # --- Windows .ico ---
    ico_path = os.path.join(ICONS_DIR, "icon.ico")
    pack_ico(src, ico_path, ICO_SIZES)
    print(f"  wrote {os.path.relpath(ico_path, ROOT)} ({len(ICO_SIZES)} sizes, transparent bg)")

    # --- in-app logo ---
    logo_path = os.path.join(PUBLIC_DIR, "logo.png")
    make_ghost_icon(src, logo_path, LOGO_PX)
    print(f"  wrote {os.path.relpath(logo_path, ROOT)} ({LOGO_PX}x{LOGO_PX}, transparent bg)")

    # --- favicon ---
    favicon_path = os.path.join(PUBLIC_DIR, "favicon.ico")
    pack_ico(src, favicon_path, FAVICON_SIZES)
    print(f"  wrote {os.path.relpath(favicon_path, ROOT)} ({len(FAVICON_SIZES)} sizes, transparent bg)")

    # --- tray icon ---
    tray_path = os.path.join(ICONS_DIR, "tray.png")
    make_ghost_icon(src, tray_path, TRAY_PX)
    print(f"  wrote {os.path.relpath(tray_path, ROOT)} ({TRAY_PX}x{TRAY_PX}, transparent bg)")

    # --- macOS .icns ---
    icns_path = os.path.join(ICONS_DIR, "icon.icns")
    pack_icns(src, icns_path, ICNS_SIZES)
    print(f"  wrote {os.path.relpath(icns_path, ROOT)} ({len(ICNS_SIZES)} sizes, transparent bg)")

    print("done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
